// <auto-generated />
using GasWebProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GasWebProject.Migrations
{
    [DbContext(typeof(GasDbContext))]
    partial class GasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GasWebProject.Models.GasComponent", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("M")
                        .HasColumnType("float");

                    b.Property<double?>("Nominal")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Name = "N2",
                            M = 28.013480000000001,
                            Z = 0.99975999999999998
                        },
                        new
                        {
                            Name = "CH4",
                            M = 16.042760000000001,
                            Nominal = 0.00050000000000000001,
                            Z = 0.99814000000000003
                        },
                        new
                        {
                            Name = "C3H8",
                            M = 44.096519999999998,
                            Nominal = 1.0000000000000001E-05,
                            Z = 0.98306000000000004
                        },
                        new
                        {
                            Name = "C2H4",
                            M = 28.05376,
                            Nominal = 4.0000000000000003E-05,
                            Z = 0.99394000000000005
                        },
                        new
                        {
                            Name = "C2H2",
                            M = 26.037199999999999,
                            Nominal = 6.9999999999999999E-06,
                            Z = 0.99270000000000003
                        },
                        new
                        {
                            Name = "C2H6",
                            M = 30.06964,
                            Nominal = 0.00014999999999999999,
                            Z = 0.99197000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
